### ISSUE TITLE
`search_for_files_containing_string` output 'wrong'

### ISSUE THREAD

**Issue by Spaceghost** [jarv/cmdchallenge#1]
# [`search_for_files_containing_string`][0]
I'll leave the command out to leave a spoiler unless it's all that important.

Here's the output I get.

```
# Print all files, one per line that contain
# the string "500".
# 
bash(0)> # Command elided
./access.log
./access.log.1
./README
bash(0)>
```
do I need to strip the `./`?

[0]: https://cmdchallenge.com/#/search_for_files_containing_string

**Comment by jarv** [comment]
Yeah that's what it wants but it should be more forgiving.
I'll fix it, thanks!

**Comment by Spaceghost** [comment]
@jarv Awesome, thank you. I'm enjoying the project, and immediately thought it'd be fun to look into doing the same for the [fish][0] shell. I could always use more brushing up on fish function writing and other one-liner tasks, if only to level up my ability to switch between bash and fish.

As a side thought, I'd love to get a digest (daily, weekly, etc.) of new challenges somehow. Email? There's always github, I suppose!

Thanks again!

[0]: https://fishshell.com/

**Comment by jarv** [comment]
Thanks! If there are more added I'll post it on twitter - https://twitter.com/thecmdchallenge , watching github works as well as the challenges are all here. You can also run them locally if you like by following the README.
