### ISSUE TITLE
remove_extensions_from_files accepting wrong answer

### ISSUE THREAD

**Issue by vvillee** [jarv/cmdchallenge#100]
```
# You have a new challenge!
# Remove the extension from all files in
# the current directory recursively.
# 
bash(0)> find . -type f -print0 | xargs -0 -I file mv file foo
# 👍 👍 👍  Correct!
```

**Comment by jarv** [comment]
Thanks for the report, it looks like we need some improvement on the tests. This commit that was contributed earlier should do it https://github.com/jarv/cmdchallenge/commit/212e55d1df30c01f1c436442948989041f37d568  I will put it live on the site when I return from traveling on Tues/Wed.  Thanks for the issue!
