### ISSUE TITLE
Cannot input "&" with AZERTY keymap

### ISSUE THREAD

**Issue by X-dark** [jarv/cmdchallenge#103]
## Summary
If I try to input the ampersand `&` character with an AZERTY keymap nothing get input. If I switch to an QWERTY keymap, it works fine.

**Comment by jcubic** [comment]
1) On what browser/OS you see the issue?
2) Do you mean belgian AZERTY? I have it on Xubuntu.
3) How to enter `&` on that keyboard?

**Comment by X-dark** [comment]
It was on Firefox on Windows. I can reproduce in Firefox and Chromium on Linux.

It is on french AZERTY, the `&` is on the same key as `1` on the numrow. It does not need modifier to be input.

**Comment by jcubic** [comment]
I think I fix it in jQuery Terminal used by cmdchallenge, can you test http://codepen.io/jcubic/pen/LxgJQG ?

**Comment by X-dark** [comment]
Yes it works. Thanks.

**Comment by jcubic** [comment]
Fixed in version 1.0.5 @jarv if you update jQuery Terminal, it will be resolved same as #23.

**Comment by jarv** [comment]
@jcubic  thanks and thanks for making jquery terminal! site is updated.

**Comment by jcubic** [comment]
If you want to support older browsers and Safari you may want to include [key property polyfill](https://github.com/cvan/keyboardevent-key-polyfill/)

**Comment by mcdado** [comment]
Well I can tell you that with Safari (non-Technology Preview) a bunch of keys don't work.

**Comment by jcubic** [comment]
Which keys? or maybe shortcuts?

**Comment by mcdado** [comment]
Backspace, Delete, arrow keys…

**Comment by jcubic** [comment]
for those keys in Safari you need to have key property polyfill, here is [browser support](http://caniuse.com/#feat=keyboardevent-key), only Technology Preview support key property.

You can test if it work by executing this from console:

```javascript
$.getScript('https://rawgit.com/cvan/keyboardevent-key-polyfill/master/index.js', function() {
    keyboardeventKeyPolyfill.polyfill();
});
```

**Comment by jarv** [comment]
the key polyfill is now on the site.
