### ISSUE TITLE
find_tabs_in_a_file/

### ISSUE THREAD

**Issue by lagden** [jarv/cmdchallenge#104]
## find_tabs_in_a_file

In my shell...
![screen recording 2017-02-07 at 19 25](https://cloud.githubusercontent.com/assets/130963/22712325/8026a414-ed6b-11e6-9bc9-fda72851f205.gif)

In challenge...
![screen shot 2017-02-07 at 19 25 33](https://cloud.githubusercontent.com/assets/130963/22712337/939065f8-ed6b-11e6-87b2-db7356e76472.png)

**Comment by 0ki** [comment]
What shell do you have? $'\t' is the correct syntax.

**Comment by lagden** [comment]
I did using fishshell...
but I changed to bash and run this: `cat xxx.txt | grep -c \\t` and works fine too...

**Comment by lagden** [comment]
Well... I'm using OSX...

using *bash*:
`grep -c $'\t' xxx.txt ` works in *cmdchallenge*

but I got the same result with that cmd: `cat xxx.txt | grep -c \\t`
