### ISSUE TITLE
cheating in two challenges

### ISSUE THREAD

**Issue by antekone** [jarv/cmdchallenge#106]
It is possible to cheat in two challenges.

Cheat 1, `corrupted_text`: It is possible to simply paste the original text from README in order to pass this challenge, like this:

    $ cat README | head -n 15 | tail -n 9 | sed -e 's/^# \(.*\)/\1/g'

Suggested solution: insert linebreaks in different places, so the text will wrap differently than in war_and_peace.txt.

Cheat 2: `print_common_lines`: It is possible to pass this challenge by using this command:

    $ cat *log* | grep -Po '\d+\.\d+\.\d+\.\d+' | sort | uniq -d

But, of course, this doesn't meet the challenge, because it will also print IPs that are duplicated in one of the files. The test passes because sample logs happen to not have any duplicated IPs.

Suggested solution: insert a line into one of the log files with a duplicated IP. So, for example, into `access.log.2` insert another line that uses '12.135.14.52' as an IP address. I think this should be enough.

**Comment by jarv** [comment]
Cheating at the moment is a little difficult to prevent as submissions are not run against random data. I have some ideas to make it a little better that can hopefully can address some of the more obvious ways you can game the challenges.

**Comment by jarv** [comment]
commands are now being run against randomized data, though not all of them have support yet. See  https://about.cmdchallenge.com/randomizers.html for more info
