### ISSUE TITLE
broke challenge

### ISSUE THREAD

**Issue by Chaos99** [jarv/cmdchallenge#107]
## Summary
- happened during duplicate faces challenge.
- site layout seems broken, even after reload
- most commands (like `echo "hello world"`) give `unknown error :(`
- some commands (like `ls`, but also complicated ones from the challenge attempts) work
- changing one tiny detail can make a working command fail (like changing the output of an echo)

## Steps to reproduce
https://cmdchallenge.com/#/remove_duplicate_lines

-manipulated IFS env variable, don't know if it was the reason

**Comment by Chaos99** [comment]
![image](https://cloud.githubusercontent.com/assets/582663/22736595/245b878c-edff-11e6-8b39-446dd53bed91.png)

**Comment by 0ki** [comment]
I think I had this error when I had not properly enabled JavaScript for all domains involved.

**Comment by jarv** [comment]
@Chaos99 Can you let me know if you are still seeing this error?

**Comment by 0ki** [comment]
It's currently giving "inux runtime spec resources: no such file or directory" to any command.

A suggestion: have a maintenance flag, that informs user that you are currently making modifications to the backend that may lead to instability.

**Comment by jarv** [comment]
thanks for the suggestion, should be resolved now.

**Comment by Chaos99** [comment]
Brought the error message once again (maybe cached?), but then continued to work properly.
(Design changes stayed though.)
Thanks!

(And boy those non-printable characters in the faces.txt are a PITA) ;)

**Comment by jarv** [comment]
Ah good, and unfortunately this wasn't planned maintenance :( Really appreciate that you are taking the time to report this, thanks!
