### ISSUE TITLE
Unknown error (/extract_ip_addresses)

### ISSUE THREAD

**Issue by spaceexperiment** [jarv/cmdchallenge#108]
https://cmdchallenge.com/#/extract_ip_addresses 
It works locally but i keep getting Unknown Error on the website.
This is the command.
`find . -name 'access.log*' -print0 | xargs -0 egrep -oh '(?:\d{1,3}\.){3}\d{1,3}'`

**Comment by jarv** [comment]
Thanks, looks like one of the disk-cleanup jobs was failing which caused the disk to fill up. Should be ok now.. Thanks for the bug report.  The commands that were working were the ones that were generated from cache.

**Comment by spaceexperiment** [comment]
Thanks for the fast response.
