### ISSUE TITLE
unkown error

### ISSUE THREAD

**Issue by aabuhasna** [jarv/cmdchallenge#109]
Note: if you are having trouble with a challenge you can see solutions here -> https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml
Search for the challenge and look for the `example:` to see one way of doing it.

If you would like to help improve the wording of a challenge description, please consider sending a pull request against https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml

## Steps to reproduce
If applicable please provide a direct link to the challenge, example: https://cmdchallenge.com/#/sum_all_numbers

**Comment by aabuhasna** [comment]
I was taking "search for file contains string" challenge when I tried to execute grep "500" * | awk '{print $1}' I got Unknown error :(

**Comment by jarv** [comment]
Thanks, can you try now? There was an issue earlier that should be resolved now.

**Comment by aabuhasna** [comment]
thanks, its working now
