### ISSUE TITLE
If the command times out, the challenge problem is accepted and it proceeds to the next problem.

### ISSUE THREAD

**Issue by phoxis** [jarv/cmdchallenge#110]
Note: if you are having trouble with a challenge you can see solutions here -> https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml
Search for the challenge and look for the `example:` to see one way of doing it.

If you would like to help improve the wording of a challenge description, please consider sending a pull request against https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml

## Steps to reproduce
If applicable please provide a direct link to the challenge, example: https://cmdchallenge.com/#/sum_all_numbers

**Comment by jarv** [comment]
dupe of https://github.com/jarv/cmdchallenge/issues/99
