### ISSUE TITLE
grep for tabs

### ISSUE THREAD

**Issue by philipbergen** [jarv/cmdchallenge#111]
## Summary

This I expect to work, but I get zero.

```sh
grep '\t' file-with-tabs.txt|wc -l
0
```

## Steps to reproduce

https://cmdchallenge.com/#/find_tabs_in_a_file

**Comment by philipbergen** [comment]
Retarded work around:
```sh
cat file-with-tabs.txt | sed 's/\t/7/g' | grep 7 | wc -l

**Comment by 0ki** [comment]
$'\t'

**Comment by antekone** [comment]
http://askubuntu.com/questions/53071/how-to-grep-for-tabs-without-using-literal-tabs-and-why-does-t-not-work

**Comment by jarv** [comment]
If you use `grep -P` this will work, re-open if you think this is still an issue. Thanks!
