### ISSUE TITLE
delete files doesn't like 'sudo !!'

### ISSUE THREAD

**Issue by matthewfield** [jarv/cmdchallenge#113]
My standard attempt of `rm -Rf ./*` failed as an attempt at recursively deleting all files and sub directories from the current working directory. Responds with some files remain. A few variations that i would normally use didn't work, so i tried the brute force approach of escalating the last command via 'sudo !!'. That hangs it.

![screen shot 2017-02-08 at 6 41 17 pm](https://cloud.githubusercontent.com/assets/2274694/22767220/da664006-ee2e-11e6-95e5-9cd9829a5c0a.png)

**Comment by jarv** [comment]
Since commands are run in a bash subshell this will not work unfortunately.  What you should see however is something like this:
```
bash(0)> sudo !!
/tmp/script.sh: line 1: sudo: command not found
```
