### ISSUE TITLE
Incorrect filename in instructions on nested directories challenge

### ISSUE THREAD

**Issue by goldnate** [jarv/cmdchallenge#114]
I finally used ls -al to see all the subdirectories, etc. and saw that the filename we are supposed to cat in this challenge is '. .the flag.txt'. However, the challenge says the full path name is '.../  /. /the flag.txt' so the second . in the filename is replaced with a /. That made the challenge WAAAAY harder than it should have been.

Note: if you are having trouble with a challenge you can see solutions here -> https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml
Search for the challenge and look for the `example:` to see one way of doing it.

If you would like to help improve the wording of a challenge description, please consider sending a pull request against https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml

## Steps to reproduce
If applicable please provide a direct link to the challenge, example: https://cmdchallenge.com/#/sum_all_numbers

**Comment by goldnate** [comment]
https://cmdchallenge.com/#/nested_dirs

**Comment by jarv** [comment]
Thanks for the issue, I just pushed the fix for this f128aadbb887b65b1cb438c104ceec808626bca3
