### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by jcubic** [jarv/cmdchallenge#115]
There are no favicon, I have few local pages without favicon in my open tabs (I don't see titles they are too small) and it's hard to find cmd challenge website.

You can generate favicon that will work in all platforms using http://realfavicongenerator.net/ you can use ASCII cmd for this like this image:

![cmd](https://cloud.githubusercontent.com/assets/280241/22852802/ae89c3c8-f044-11e6-8775-49801e2427c4.png)

**Comment by jarv** [comment]
Thanks for the reminder and the nice suggestion, for now I am using the same one I am on the about blog. Thanks!
