### ISSUE TITLE
Completing all challenges take to first challange

### ISSUE THREAD

**Issue by jcubic** [jarv/cmdchallenge#116]
I've completed all the challanges and it ask be to complete 1 challenge https://cmdchallenge.com/#/hello_world there should be some kind of message with congratulations and that the person should come back after a while because there me be other challenges.

**Comment by jcubic** [comment]
It seems that there is a message: "You are officially a command line master, great job!"

**Comment by jarv** [comment]
Hacking on something today that I think will be neat for something to show when all challenges are completed. If you have some ideas I would love to hear them, unfortunately my front-end coding skills are not great.
