### ISSUE TITLE
Cannot enter characters with AltGr+<key>

### ISSUE THREAD

**Issue by mbollmann** [jarv/cmdchallenge#118]
On a German keyboard layout, you need to press AltGr + a certain key to get certain characters, like a backslash or the pipe symbol. I cannot enter any character at all that requires AltGr to be pressed, which means the page is almost unusable without switching keyboard layouts. Why does that happen?

**Comment by vikman90** [comment]
Hi,

I have the same problem with a spanish keyboard. I cannot type characters like "|", "\", "{" "}", "[" or "]". It worked properly last week.

**Comment by jarv** [comment]
Opened https://github.com/jcubic/jquery.terminal/issues/288 , worst case I guess we can just rollback to the old version though I would prefer to keep it as it fixes https://github.com/jarv/cmdchallenge/issues/103

**Comment by jcubic** [comment]
It work for me using latest file from master branch can you confirm that it also work for you? Could you test this [code pen](http://codepen.io/jcubic/pen/MbVMwO)? It will be in version 1.0.6.

**Comment by jarv** [comment]
Just pushed an update to the site that has https://github.com/jcubic/jquery.terminal/commit/305350682858b6b3f4f75eae8efcd35103fbd53e  please let me know if you still see issues.

**Comment by mbollmann** [comment]
Works for me now!

**Comment by jcubic** [comment]
Version 1.0.6 with a fix is released.
