### ISSUE TITLE
Use bash.hook.io for excecuting commands

### ISSUE THREAD

**Issue by reimertz** [jarv/cmdchallenge#119]
First, love the idea and execution of cmdchallenge! 👏

It was just a teeny-weeny slow for me, which I assume is related to the amount of users you have now. Congrats!

I wonder if you have played around with other solutions rather than self-hosted BE? I think hook.io/gateways might be a good fit, that would mean that you could have all the static content hosted on github, and then use bash.hook.io to excecute commands.

Here is an example: http://bash.hook.io/?source=echo "hello world"

**Comment by jarv** [comment]
Thanks for the suggestion, executing what is given in bash using this or https://github.com/Stackvana/microcule (which I think is what it uses under the covers) would definitely be faster.

A few problems I see however:

* For hook.io I looked at their pricing, it's very expensive.
* cmdchallenge gives you a full linux environment for whatever command you type, can this do the same? For example: http://bash.hook.io/?source=%22perl%20--version%22

There are probably some things I can do to speed things up, for example when you type "echo hello world" this is actually returned from cache but it still needs to do a couple dynamodb queries which probably accounts for the latency.
