### ISSUE TITLE
deleting all files doesn't accept obvious answer

### ISSUE THREAD

**Issue by masukomi** [jarv/cmdchallenge#12]
```
# Delete all of the files in this challenge
# directory including all subdirectories and
# their contents.
# 

```
i responded with `rm -rf *` and it didn't work. `whoami` says i'm `root` so... either i'm missing something obvious... or this isn't working right

it responded with `False` though, which is odd...

```
bash(0)> rm -rf *
False
```

**Comment by jarv** [comment]
`rm -f *` by default will not remove dotfiles which is the reason why it doesn't work.

**Comment by masukomi** [comment]
ahhh. i didn't realize there were dotfiles, and the instructions didn't mention them either. That feels more like a gotcha to me. As nothing so far has tried to sneak anything in I think the instructions should be modified to include a note about dotfiles. maybe

Delete all of the files in this challenge directory including all the dotfiles, subdirectories, and their contents.

**Comment by masukomi** [comment]
also the "False" shouldn't be there because that doesn't normally happen, and, as this is a expected failure that you're specifically looking for (thus `.dont.forget.dotfiles`) you should probably let folks know that that's what they screwed up.

**Comment by Gunstick** [comment]
You never do an ls before deleting? And always use the -a option!
```
bash(0)> ls -a
.
..
.config
.dont.forget.dotfiles
README
animi.doc
[...]

```

**Comment by jarv** [comment]
@masukomi  you are absolutely correct that it shouldn't be returning "False". I will leave this issue open until that is resolved.

**Comment by masukomi** [comment]
also... 

```
find . -exec rm -rf '{}' \;
# and 
rm -rf * .*
```

aren't accepted. I'm guessing that what's happening is that the tool is seeing the error code  that both produce and assuming failure, but it does actually work even though they also return an error code. Test should be modified to see if there are actually no files in the directory instead of assuming error code == failure. 

(yes, i've been intentionally trying some esoteric solutions on these)

**Comment by jarv** [comment]
Yeah your guess is correct and that if it returns non-zero it assumes failure, something I didn't consider.

**Comment by masukomi** [comment]
> You never do an ls before deleting? And always use the -a option!

@Gunstick this isn't a normal scenario. normally i care about the possibility of accidentally deleting things i shouldn't. in this scenario blowing up the world is the desired outcome, and they're not my files anyway, so i didn't check. 

also `ls -lash` is more fun to type. for me it's either `ls` or i give it the lash! ;)

**Comment by jarv** [comment]
This has been fixed and is now an accepted answer:

```
bash(0)> find . -exec rm -rf '{}' \;
rm: refusing to remove '.' or '..' directory: skipping '.'
find: './.config': No such file or directory
find: './var': No such file or directory
# 👍 👍 👍  Correct!
# You have a new challenge!
# Count the number of files in the current
# working directory. Print the number of
# files as a single integer.
# 
bash(1)>
```
