### ISSUE TITLE
Unclear description in reverse_readme

### ISSUE THREAD

**Issue by gitunique** [jarv/cmdchallenge#123]
Current description for the reverse_readme challenge is ambiguous. Current instructions are:

Print the lines of the README file in this directory in reverse
~~~~~~~~~~~~~~~~~~~~~
In the future
Environmental destruction will be the norm
No longer can it be said that
My peers and I care about this earth
It will be evident that
My generation is apathetic and lethargic
It is foolish to presume that
There is hope
~~~~~~~~~~~~~~~~~~~~~
-Jonathan Reed "The Lost Generation"

This could be interpreted as printing each line in reverse, as opposed to reverse line order (print the last line first and the first line last). Suggest updating the description to state 'reverse line order' with the hint being 'first line last'.

That side, a new challenge could be printing the text of each line in reverse, with the solution being something like: `while read line; do echo $line | rev; done < README`

**Comment by jarv** [comment]
Thanks! fixed in https://github.com/jarv/cmdchallenge/commit/eb8a4844a80945b0cb2a4ccff63a9023c4c10975. Also feel free to open up a PR next time if you have suggestions.
