### ISSUE TITLE
Files starting with a number, solution isn't accepted?

### ISSUE THREAD

**Issue by neilk** [jarv/cmdchallenge#13]
To me, this looks right:

```
(for f in `find . -type f`; do basename $f; done;) | grep -e '^[0-9]' | sort
```

But it's not accepting the solution?

**Comment by joshtriplett** [comment]
@neilk Consider how your proposed solution would work if any filenames contain spaces.

**Comment by dobladov** [comment]
Should be valid this solution?  This returns also filenames with spaces.

`find .  -name '[0-9]*' -printf "%f\n"`

**Comment by dobladov** [comment]
In my case was my fault, I didn't filter by file.

`find . -type f -name '[0-9]*' -printf "%f\n" `

**Comment by pnebert** [comment]
false solution is also accepted
`find . -type f -name '[0-9a-Z]*' -printf '%f\n'`

**Comment by 0ki** [comment]
@pnebert This is a correct solution as ironically a-Z is not a valid range.

**Comment by pnebert** [comment]
@0ki so invalid ranges getting ignored? what about [0-9]*, normally it means none to infinite count of only numbers, but it would not match filenames with characters in it
