### ISSUE TITLE
file-with-tabs.txt Docker API error

### ISSUE THREAD

**Issue by tato69** [jarv/cmdchallenge#132]
I get a Docker API error as below:

# How many lines contain tab characters in
# the file named "file-with-tabs.txt" in the
# current directory.
# 
bash(0)> grep  $'\t' file-with-tabs.txt | wc -l
Docker API error
bash(☠️)> 

This should work as tested on a separate box:

root@kali:~/git# cat tab
        a
        b
        c
        d
        e
root@kali:~/git# grep $'\t' tab
        a
        b
        c
        d
        e
root@kali:~/git# grep $'\t' tab | wc -l
5

**Comment by jarv** [comment]
Thanks for the report, started noticing more of these errors recently and will update this issue when it is fixed.

**Comment by jarv** [comment]
There were memory issues on the host that are now resolved.
Thanks again for the report.

```
bash(124)> grep $'\t' file-with-tabs.txt | wc -l
3
# 👍 👍 👍  Correct!
# You have a new challenge!
# There are some files in this directory that
# start with a dash in the filename.
# Remove those files.
# 
```
