### ISSUE TITLE
print_number_sequence alternative solution

### ISSUE THREAD

**Issue by fibo** [jarv/cmdchallenge#144]
## Steps to reproduce

https://cmdchallenge.com/#/print_number_sequence

I expected that `seq 1 100 | tr '\n'  '  '` would be a solution, it produces the same output as the example `echo $(seq 1 100)`

**Comment by mtak** [comment]
It seems the problem is that `tr '\n' ' '` also cuts off the last newline character. The challenge doesn't specify you should preserve this newline though.

**Comment by jarv** [comment]
Yeah, the newline at the end is significant which is the case for all of the challenges, maybe we can improve the wording.

**Comment by fibo** [comment]
Ah ok, thank you I missed it. The output of both commands looked almost the same and also I could not immagine the right solution.
