### ISSUE TITLE
Bash regex match times out

### ISSUE THREAD

**Issue by ecksun** [jarv/cmdchallenge#150]
## Summary

Bash command with regex match times out

## Steps to reproduce

https://cmdchallenge.com/#/files_starting_with_a_number

    bash(0)> [[ '737Jeffrey' =~ [[:digit:]] ]] && echo "woo"
    Command timed out

**Comment by ecksun** [comment]
This might in fact be related to issue #136

**Comment by jarv** [comment]
Thanks for the report, it looks like all non-cached commands are timing out right now, I will update the issue when it is resolved.

**Comment by jarv** [comment]
OK It looks like I just got a huge spike in traffic and I am having trouble keeping up.

**Comment by 0ki** [comment]
You are being reddited: https://www.reddit.com/r/linux/comments/6us6p1/commandline_challenge_test_your_skills/

**Comment by jarv** [comment]
Sigh.. Sadly I had just switched over some new terraform stuff for provisioning and hadn't yet made it easy to add more servers to handle the non-cached submissions. Just added some more capacity so it should be better now.
