### ISSUE TITLE
Slight grammatical error in a message

### ISSUE THREAD

**Issue by timmyg558** [jarv/cmdchallenge#153]
![cmdchallengegrammar](https://user-images.githubusercontent.com/28305526/29499195-a31ac782-85d9-11e7-911a-3fa116a8ab66.JPG)
Note: if you are having trouble with a challenge you can see solutions here -> https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml
Search for the challenge and look for the `example:` to see one way of doing it.

If you would like to help improve the wording of a challenge description, please consider sending a pull request against https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml

## Summary
There is a slight grammatical error on one of the congratulatory messages. It should read "I'm impressed at how far you've gotten... keep at it!". I have attached a screenshot of the message as it reads. Thanks for the great challenge, it has been really fun!!!

## Steps to reproduce
If applicable please provide a direct link to the challenge, example: https://cmdchallenge.com/#/sum_all_numbers

**Comment by jarv** [comment]
Thanks for the issue, site is now updated.
https://gitlab.com/jarv/cmdchallenge-site/commit/27b5b171dde6c306d06d2f538ee0c19910cedb71
