### ISSUE TITLE
print_number_sequence

### ISSUE THREAD

**Issue by blentzgh** [jarv/cmdchallenge#154]
$ seq -s \  100 >1 # accepted answer
$ seq 100 | tr "\n" " " >2 # non-accepted answer
$ cksum 1 2 # output is identical
2127114782 292 1
2127114782 292 2

**Comment by 0ki** [comment]
no, it's not
```1219010504 292 1
2127114782 292 2
```

Look carefully at the whitespace.

**Comment by blentzgh** [comment]
TF? What version of GNU coreutils are you using? My checksums are identical... they don't lie... white space differences would have shown up in cksum.

Can you run both outputs through od -x ?

**Comment by 0ki** [comment]
$ diff <(seq -s \  100 | od) <(seq 100 | tr "\n" " " | od)
    19c19
    < 0000440 030061 005060
    ---
    > 0000440 030061 020060

I cannot image why should they be identical.
Also see #156.

**Comment by blentzgh** [comment]
Closing as duplicate of https://github.com/jarv/cmdchallenge/issues/156
