### ISSUE TITLE
Can't solve puzzle disp_table

### ISSUE THREAD

**Issue by pholat** [jarv/cmdchallenge#155]
## Summary
Can't solve puzzle: https://cmdchallenge.com/?utm_source=nixcraft#/disp_table with resolution below

## Steps to reproduce
Provide solution:
`while read line; do printf "%-7s" $( sed 's/,/ /g' <<< $line ); echo "" ; done < table.csv`
See that resolution is not accepted. 
Most probably due to additional spaces at the end of line?

I saw similar issue when solving: 
https://cmdchallenge.com/?utm_source=nixcraft#/print_number_sequence
With `for + printf` instead `seq`

**Comment by jarv** [comment]
I think this is indeed a bug as for this challenge I would ignore blank space at the end of lines.

**Comment by pholat** [comment]
Thanks, it's appreciated.

Ps. I've enjoyed em a lot, good work :)
