### ISSUE TITLE
Don't understand why this doesn't work..

### ISSUE THREAD

**Issue by NickeZ** [jarv/cmdchallenge#16]
```
# You have a new challenge!
# Extract all IP addreses from files that
# that start with "access.log" printing one
# IP address per line.
# 
bash(0)> find . -name access.log* | xargs grep -h 500 | cut -f1 -d' '
69.16.40.148
225.219.54.140
2.71.250.27
```

**Comment by jarv** [comment]
`bash(0)> find . -name access.log* | xargs cut -f1 -d' '` should work fine.

**Comment by QuLogic** [comment]
You've made a big assumption about where the IP addresses might be.

**Comment by MasWag** [comment]
How about this?
find . -name access.log -exec grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' {} \; | awk -F . '$1<256&&$2<256&&$3<256&&$4<256'

**Comment by xspager** [comment]
try using awk to get the first column
... | awk '{print $1}'
