### ISSUE TITLE
dead link dirs_containing_files_with_extension under user submitted solutions. 

### ISSUE THREAD

**Issue by mmlopez** [jarv/cmdchallenge#162]
Note that the cmdchallenge.com official code repo is on GitLab, https://gitlab.com/jarv/cmdchallenge

If you are having trouble with a challenge you can see solutions here -> https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml
Search for the challenge and look for the `example:` to see one way of doing it.

If you would like to help improve the wording of a challenge description, please consider sending a pull request against https://gitlab.com/jarv/cmdchallenge/blob/master/challenges.yaml

## Summary
Click on dirs_containing_files_with_extension link on the solutions area and that will allow you to duplicate the dead link.

## Steps to reproduce
If applicable please provide a direct link to the challenge, example: https://cmdchallenge.com/s/#/dirs_containing_files_with_extension

The issue is that the  'See user submitted solutions for this challenge' for the above (dirs_containing_files_with_extension) challenge is a dead link that does not show any  solutions but instead stays on the same page with no error being generated.

Duplicated in firefox and chrome.

**Comment by stricklerxc** [comment]
Looks like a 403 Forbidden error when attempting to pull the solutions from https://cmdchallenge.com/s/solutions/dirs_containing_files_with_extension.json. Might be a permissions error with CloudFront or S3 for that particular file.

**Comment by jarv** [comment]
Sorry for the slow response here, this is resolved now.
