### ISSUE TITLE
Placing ?? as input causes a 400 bad request

### ISSUE THREAD

**Issue by sukima** [jarv/cmdchallenge#17]
<img width="1430" alt="screen shot 2017-01-26 at 18 07 31" src="https://cloud.githubusercontent.com/assets/70075/22354227/65e979d2-e3f2-11e6-969b-64dbc455325b.png">

## To Reproduce

1.  Type `??`.
2.  Press <kbd>Enter</kbd>.

**Comment by bmoyles** [comment]
attempted to use `rm -rf ./* ./.??*` and received an internal server error

**Comment by zoff99** [comment]
![error](https://cloud.githubusercontent.com/assets/6833516/22376084/e5992fc8-e4ac-11e6-9a88-2ee6689046c0.PNG)

**Comment by jarv** [comment]
This is fixed now, it was due to this weird behavior with jQuery https://stackoverflow.com/questions/5707619/uncomprehensible-jquery-ajax-behavior-when-data-contains-consecutive-questio
