### ISSUE TITLE
No touchy the scrollbar!

### ISSUE THREAD

**Issue by phs** [jarv/cmdchallenge#20]
Fun game.  I touched my mouse wheel to look at the scroll back buffer and noticed something is molesting the normal feel/speed of it.  Plops on that!  Please leave the scroll bars alone.

**Comment by jarv** [comment]
Can you expand a little bit on the "normal feel" that you are expecting? Not sure I've seen the same behavior.

**Comment by phs** [comment]
The effect appears to be gone now.  It felt like a bad smooth-scroll implementation.  Nevermind! ^__^
