### ISSUE TITLE
Challenge count_files/ should have hidden files

### ISSUE THREAD

**Issue by mrquincle** [jarv/cmdchallenge#21]
Currently your example in https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml uses `ls` to count files. This will not work for hidden files.

Better to allow people to get in the habbit of using `find . -type f` for things like counting. 

Including hidden files might be one way to make people think about that.

**Comment by BlitzKraft** [comment]
Another bug with this challenge - currently `echo 2` is being accepted as a solution. May be give echo the same treatment as `ls`?

**Comment by jarv** [comment]
@mrquincle Good point, feel free to send a PR with the fix or I will get around to changing it later.
@BlitzKraft  I haven't implemented a way yet to test against random input, for now it is open in the sense that you can accomplish the same things via many commands but obviously if you "echo 2" you are cheating :)

**Comment by BlitzKraft** [comment]
@jarv I agree it's cheating. I was wondering if there could be a way to prevent that. It's a trivial solution but I was wondering if there is a way to prevent that from being counted as a solution.

**Comment by jarv** [comment]
Yeah I think the common way to prevent this would be to have randomized
inputs, like a random set of files, and test commands against them.

**Comment by jarv** [comment]
https://cmdchallenge.com/#/count_files now checks against random data to prevent cheating

**Comment by mrquincle** [comment]
That was not the bug, but the hijack of this thread by @BlitzKraft.

**Comment by BlitzKraft** [comment]
¯\\\_(ツ)\_/¯

I thought that was just a different manifestation of the same issue/bug.
