### ISSUE TITLE
stdout is not included in output

### ISSUE THREAD

**Issue by wolfgang42** [jarv/cmdchallenge#22]
For `sum_all_numbers`, I tried the following:

```
cat sum-me.txt | tr '\n' '+' | sed 's/\+$//' | bc
```

For some reason, this prints no output and exits with status 0. `echo '1+2+3' | bc` outputs `6` as expected, so the only thing I can think of is that the answer is being swallowed somehow.

For whatever it's worth, I eventually wound up solving the challenge with:
```
echo 42
```
which I would expect to produce the same output, and which succeeded.

**Comment by jarv** [comment]
You will need to add a linefeed at the end for bc, this will work:

```
 cat sum-me.txt | tr '\n' '+' | sed 's/\+$/\n/'  | bc
```

bc is throwing a syntax error but it is not getting back to the user unfortunately with your command which is an issue.

**Comment by wolfgang42** [comment]
Aha, now I see what I did wrong. It hadn't occurred to me that I was stripping the trailing newline, since in my shell that would cause the prompt to crash into the output, but of course in a web terminal that's not going to happen. 😄 

It looks like data on stdout is being lost (`echo foo >&2` also prints nothing) so I've changed the title accordingly.

**Comment by wolfgang42** [comment]
Actually, come to think of it this might explain some problems I had with a few other challenges as well...

**Comment by jarv** [comment]
The behavior before was to fail on non-zero exit codes and not display stderr by default. I just deployed a change so that it will be default not fail on non-zero returns and print stderr. Please let me know if you see any more issues and thank you very much for taking the time to file an issue!
