### ISSUE TITLE
search_for_files_containing_string doesn't accept command "grep -rl '500' ."

### ISSUE THREAD

**Issue by jacy** [jarv/cmdchallenge#27]

**Comment by acarl005** [comment]
+1

**Comment by camflan** [comment]
+1

**Comment by jarv** [comment]
There was a server issue below that is resolved now, thanks for reporting it:

bash(2)> grep -rl '500' *
README
access.log
access.log.1
# 👍 👍 👍  Correct!
# You have a new challenge!
# Print the relative file paths, one path
# per line for all files that start with
# "access.log" in the current directory.
# 
bash(0)>
