### ISSUE TITLE
replace_text_in_files Internal Server error

### ISSUE THREAD

**Issue by mbubb** [jarv/cmdchallenge#28]
Thanks for this it is fun

https://cmdchallenge.com/#/replace_text_in_files

This works for me on a Centos6 box but I get an Internal Server error here

find ./ -iname "*.txt" -print0 | xargs -0 sed -i 's/challenges are difficult//g'

I realize the files have spaces in the name - not sure why this is not working

thank you

**Comment by jarv** [comment]
Thanks for filing an issue, this should be resolved now. Let me know if you still see a problem.
