### ISSUE TITLE
Most of my attempts result in Internal Server Error

### ISSUE THREAD

**Issue by korvus81** [jarv/cmdchallenge#29]
I have no idea what I'm doing wrong...  It's possible none of these would work, but I've been able to execute things without an error on earlier steps.
```# You have a new challenge!
# Extract all IP addreses from files that
# that start with "access.log" printing one
# IP address per line.
# 
bash(0)> find . -iname 'access.log*' | xargs egrep -h -o '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+'
Internal Server Error
bash(☠️)> egrep -h -o '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+' `find . -iname 'access.log*'`
Internal Server Error
bash(☠️)> grep -h -o '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+' `find . -iname 'access.log*'`
Internal Server Error
bash(☠️)> for f in `find . -iname 'access.log*'`; do grep -h -o '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+' $f; done
Internal Server Error
bash(☠️)>
```

There are a few of the challenges like this that I can't seem to find a command that doesn't produce an internal server error...  In 'replace_text_in_files' some lines as simple as `echo a` are returning an error.

**Comment by jarv** [comment]
Thanks for filing an issue, this should be resolved now. Let me know if you still see a problem.
