### ISSUE TITLE
access.log is not there

### ISSUE THREAD

**Issue by shkesar** [jarv/cmdchallenge#3]
I'm on the initial exercises where I'm supposed to search for patterns within the files starting with "access.log" and I've tried several commands that didn't work but they all work on my local pc.

The error message says that the file access.log doesn't exist.

**Comment by jarv** [comment]
Hi shkesar - can you link to the challenge and the command you tried in the terminal?

**Comment by klausmeyer** [comment]
Similar or maybe even the same issue here:

```

 _____ _____ ____     _____ _____ _____ __    __    _____ _____ _____ _____ 
|     |     |    \   |     |  |  |  _  |  |  |  |  |   __|   | |   __|   __|
|   --| | | |  |  |  |   --|     |     |  |__|  |__|   __| | | |  |  |   __|
|_____|_|_|_|____/   |_____|__|__|__|__|_____|_____|_____|_|___|_____|_____|
                
[contribute on github] [report an issue]
[reset] [twitter] [contact]
			
Are you up for the command line challenge?
Solve the tasks printed below in a single
line of bash.
 
# Print "hello world".
# Hint: There are many ways to print text on
# the command line, one way is with the 'echo'
# command.
# 
# Try it below and good luck!
# 
# You have a new challenge!
# Print all matching lines (without the filename
# or the file path) in all files under the current
# directory that start with "access.log" that
# contain the string "500".
# 
bash(0)> pwd
/var/challenges/search_for_string_in_files_recursive
bash(0)> ls
README
var
bash(0)>
```

**Comment by jarv** [comment]
The recursive part means you will need to traverse into the var/ directory.
Here is what the directory structure looks like:

bash(0)> find .
.
./var
./var/log
./var/log/httpd
./var/log/httpd/access.log.2
./var/log/httpd/access.log
./var/log/httpd/access.log.1
./README

**Comment by klausmeyer** [comment]
Right. Just read the intro again 😁 
Sorry, just thought I could help here.

**Comment by shkesar** [comment]
It’s so good to hear back from you so fast. I’m on challenge:search_for_string_in_files_recursive/<https://cmdchallenge.com/#/search_for_string_in_files_recursive>

Here I have tried a few possibilities:

grep -h 500 access.log*
cat access.log* | grep 500

And 3 or four more possibilities utilising ls and cat just so in order I can get the result but it doesn’t work. I hope those are correct commands I’m putting on or I’m doing something stupidly wrong.

But I tried refreshing the page and even resetting the session but it didn’t work.
A `ls` command shows that there are no such files with access.log* named pattern.

It just shows a var folder and a README.

**Comment by jarv** [comment]
Here is a solution (one of them) if you give up and want to see an answer - https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml#L117

**Comment by shkesar** [comment]
Oh that was my mistake. Thanks for the quick response.
Recursive search it is then.

**Comment by shkesar** [comment]
This is a good warm up. Thanks for building this @jarv
