### ISSUE TITLE
Search for Files Containing String should have multiple correct answers.

### ISSUE THREAD

**Issue by rubbsdecvik** [jarv/cmdchallenge#35]
# Expected behavior

Given the following instructions for the module [`search_for_files_containing_string`](https://cmdchallenge.com/#/search_for_files_containing_string):

```sh
# Print all files, one per line that contain
# the string "500".
```

The command:

```sh
grep -l 500 ./*
```

Which outputs:

```sh
./README
./access.log
./access.log.1
```

Should be a valid alternative correct answer. 

# Observed Behavior

The command:

```sh
grep -l 500 *
```

Which outputs:

```sh
README
access.log
access.log.1
```

is the only valid answer.

# Possible Investigation Area

I believe the lines [here](https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml#L93-L96) may be the key.

I'm not sure enough how this is implemented if multiple answers can be correct, however, I believe that the `./` addition to most commands that work on a path is good practice. After all, [Explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/).

**Comment by rubbsdecvik** [comment]
PS: Now that the formal bug report is in, I just want to say that this was/is fun. Thanks for doing this!

**Comment by jarv** [comment]
Thank you for this very well written issue and I'm sorry it took awhile to respond. I have taken your suggestion and make your solution valid for the challenge.  Thanks!

**Comment by rubbsdecvik** [comment]
No worries on the time frame. It's not like it was super crucial.
