### ISSUE TITLE
increase difficulty of remove_extensions_from_files with spaces

### ISSUE THREAD

**Issue by Gunstick** [jarv/cmdchallenge#37]
this challenge, including the solution in the yaml, does not account for spaces in filenames.
As this problem is very often an issue, a file with blanks should be in the list.

**Comment by Gunstick** [comment]
For tackling that problem I usually use the "find . |while read f" construct

**Comment by jarv** [comment]
Thanks for the suggestion! I am also happy to take pull requests if you want to add to or modify the challenges.

**Comment by 0ki** [comment]
There is another challenge or two that have spaces in them, so it does come up eventually.
