### ISSUE TITLE
corrupted text solution does not work

### ISSUE THREAD

**Issue by zoff99** [jarv/cmdchallenge#38]
bash(0)> cat war_and_peace.txt |sed -e 's#![!]*#!#g'|sed -e 's# !# #'|sed -e 's#! \([a-z]\)# \1#g'|sed -e 's#\([a-z]\)!\([a-z]\)#\1\2#g'|sed -e 's#!\.!#.#'
Command is too long.

**Comment by zoff99** [comment]
![aaaaaaa](https://cloud.githubusercontent.com/assets/6833516/22376569/db63d326-e4ae-11e6-81c0-7c290a5f94f5.png)

**Comment by jarv** [comment]
nice one! I will increase the length limit.

**Comment by tblancher** [comment]
You also don't need to type sed more than once, and you can get rid of the cat.  Try this:

sed 's/$pattern1//g;s/$pattern2//...' war_and_peace.txt
