### ISSUE TITLE
Print Number Sequence

### ISSUE THREAD

**Issue by grymoire** [jarv/cmdchallenge#40]
This seems to be a valid answer to the challenge "Print Number Sequence"
echo {1,2,3,4,5,6,7,8,9} {1,2,3,4,5,6,7,8,9}{0,1,2,3,4,5,6,7,8,9,0} 100

**Comment by tblancher** [comment]
That is valid, though not very efficient for the person typing it.  I did it much more succinctly.

**Comment by jarv** [comment]
I like it! With these challenges I am looking forward to seeing the more creative solutions. I'll have a post soon about some of the more interesting ones.
