### ISSUE TITLE
Color scheme is hard to read

### ISSUE THREAD

**Issue by David-Gould** [jarv/cmdchallenge#42]
The blue and green colors against the dark background are hard to read, especially the challenge question itself. I think more contrast would help, or maybe make it possible to choose color schemes.

**Comment by jarv** [comment]
I confess I am terrible when it comes to front-end design and colors, thanks for the suggestion! I actually just copied the colors from the color scheme of my text editor.

**Comment by David-Gould** [comment]
On Sat, 28 Jan 2017 02:06:39 -0800
John Jarvis <notifications@github.com> wrote:

> I confess I am terrible when it comes to front-end design and colors, thanks for the suggestion! I actually just copied the colors from the color scheme of my text editor. 

It's actually a hard problem, most color schemes are ok for some people on
some displays in some lighting. For example your page is legible to me at
night, but with daylight coming in the window there is not enough contrast to
overcome the ambient lighting. You might consider solarized, many people like
it and it has a dark and a light scheme. I tried it, and it's not bad, but
frankly my preference is for black text on white backgrounds with minimal
highlighting. There is no pleasing everyone of course.

Notwithstanding all that, I love what you have done and have been pointing
junior colleagues at it as a way to level up.

-dg

-- 
David Gould              510 282 0869         daveg@sonic.net
If simplicity worked, the world would be overrun with insects.

**Comment by jarv** [comment]
Closing this as I think I will keep the color scheme as-is for now.
