### ISSUE TITLE
How to correctly remove file in delete_files

### ISSUE THREAD

**Issue by luckv** [jarv/cmdchallenge#44]
I tried many answers:

- `rm -fr`
- `rm -fr ./*`
- `rm -fr *`
But none of them do the work. I tried deleting a single file, but it remains where it is

**Comment by jarv** [comment]
Answers are here https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml#L162 if you want to take a look, though there are many ways to do the same thing of course.
