### ISSUE TITLE
rm -rf * can be used to solve remove_extensions_from_files

### ISSUE THREAD

**Issue by est31** [jarv/cmdchallenge#47]
Apparently it doesn't check for the presence of files.

**Comment by 0ki** [comment]
Valid report.
This sucks. :(

**Comment by avioli** [comment]
`rm -rf *` removes all files, but not the ones with `.` in front of the name. You have to remove them too. Check `ls -la`.

**Comment by avioli** [comment]
No, you have to have 9 remaining files.

**Comment by avioli** [comment]
Ah, there's a commit from 21 minutes ago. My bad.

**Comment by est31** [comment]
Fixed by 212e55d1df30c01f1c436442948989041f37d568 (#94)
