### ISSUE TITLE
Issue with remove_extension_from_files

### ISSUE THREAD

**Issue by nakuljavali** [jarv/cmdchallenge#48]
Tried this:
Even though the solutions seems to be correct, no error was thrown.

`find . -type f | while read line; do new=`echo $line | cut -d. -f2`; mv $line .$new 2>/dev/null ; done`

Thanks!

**Comment by jwbensley** [comment]
If you are talking about this challenge it is also not working for me: https://cmdchallenge.com/#/remove_extensions_from_files

I am trying the following:

```
# Remove file extensions
# ****************************
# Remove the extension from all files in
# the current directory recursively
#
bash(0)> find . -type f | xargs basename -a | awk -F "." '{print $1}'
error
corporis
odit
animi
necessitatibus
totam
beatae
README
libero

bash(1)> find . -type f
./error.doc
./2038/01/19/corporis.xls
./2038/01/19/odit.doc
./2038/01/19/animi.doc
./necessitatibus.doc
./totam
./beatae.flac
./README
./libero.xls
```
That looks correct to me, all file names without the path or file extension.

I can see here that there is no valid expected_output: https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml#L376

**Comment by jarv** [comment]
For this challenge you need to remove the extensions, not just print the files without extensions on the terminal. Maybe the wording of the description can be improved?

**Comment by pnebert** [comment]
i try this challenge with
`find . -type f -name '*.*' -printf '%P\n' | xargs rename 's/\..*$//'`

but i get
`find: 'rename' terminated by signal 9`

**Comment by 0ki** [comment]
#82
