### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by netikras** [jarv/cmdchallenge#49]
bash(☠️)> print  "hello world"
Internal Server Error
bash(☠️)> echo
Internal Server Error

**Comment by jarv** [comment]
I was doing a bit of maintenance on the database which is probably the reason for this, is it working better now?

**Comment by netikras** [comment]
Still no joy...

# Try it below and good luck!
# 
bash(0)> echo
Internal Server Error
bash(☠️)> print
Internal Server Error
bash(☠️)> pwd
Internal Server Error
bash(☠️)> whoami
Internal Server Error
bash(☠️)> 
find    echo    awk    sed    perl    wc    grep    access.log    cat    sort    README    clear    exit
bash(☠️)> echo hello world
Internal Server Error
bash(☠️)>

**Comment by netikras** [comment]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by netikras** [comment]
https://4olr6tg27l.execute-api.us-east-1.amazonaws.com/prod

**Comment by netikras** [comment]
cmdchallenge.js:1 Object

**Comment by jarv** [comment]
Do you have any adblockers or other extensions? It might be the problem, can you temporarily try disable them and try again?

**Comment by netikras** [comment]
you're right, it was the javascript blocker :)

Nice toy :) quite slow though...
