### ISSUE TITLE
Spoilers in issues

### ISSUE THREAD

**Issue by Spaceghost** [jarv/cmdchallenge#51]
Can we have an ISSUES file to describe how to file an issue without spoilers, and describe how to get help with specifics outside of the issue, or is that unreasonable for the github repo?

Seeing parts of challenge solutions seems fine, but having the whole thing there ruins my personal curiosity as a user while I'm paying attention to the project as a developer and interested chum.

**Comment by jarv** [comment]
I added an ISSUES file and referenced the challenges.yaml for those who are seeking help with the solutions.
