### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by netzverweigerer** [jarv/cmdchallenge#52]
bash(0)> tail -n 5 access.log
Internal Server Error
bash(☠️)>

**Comment by thePalindrome** [comment]
That happens constantly, even for more simple commands.
The server is just overloaded because it wasn't expected to get this popular :P

**Comment by jarv** [comment]
"Internal Server Error" is a default generic error unfortunately. I make the message better.
Seems to be ok for me:

```
# You have a new challenge!
# Print the last 5 lines of "access.log".
# 
bash(0)> tail -n 5 access.log
199.37.62.156 - - [09/Jan/2017:22:42:18 +0100] "GET /posts/1/display HTTP/1.0" 200 2477
55.74.240.123 - - [09/Jan/2017:22:44:25 +0100] "POST /posts/1/display HTTP/1.0" 200 3471
251.111.109.143 - - [09/Jan/2017:22:49:02 +0100] "GET /posts/foo?appID=xxxx HTTP/1.0" 200 2477
101.163.230.250 - - [09/Jan/2017:22:52:31 +0100] "DELETE /posts/2/display HTTP/1.0" 404 2477
200.19.168.148 - - [09/Jan/2017:22:57:11 +0100] "GET /posts/foo?appID=xxxx HTTP/1.0" 200 3471
# 👍 👍 👍  Correct!
# You have a new challenge!
# Print the relative file paths, one path
# per line for all filenames that start with
# "access.log" in the current directory.
# 
```

Any chance you have a browser extension or add blocker preventing the ajax post to https://4olr6tg27l.execute-api.us-east-1.amazonaws.com/prod ?

**Comment by thePalindrome** [comment]
Nope, that line will fail sometimes and succeed other times!

If you ran that code 12 times, you'd see plenty of times where it errors out.

**Comment by jarv** [comment]
Yeah I see it now, taking a look

**Comment by jarv** [comment]
OK added more database capacity and I hope it is better now, do you see any more internal server errors?

**Comment by jarv** [comment]
This should be resolved, please reopen if you see more issues. Thanks for the bug report!
