### ISSUE TITLE
Unsupported Kernel

### ISSUE THREAD

**Issue by thePalindrome** [jarv/cmdchallenge#55]
The kernel running on the website is 4.7.3, while the oldest barely supported kernel is 4.8.17 with  	4.9.6 being suggested.

I would presume the ancient version is due to coreos only having it, but is there any possibility to have a more up to date server?

Sources: https://kernel.org/
[code]uname -a[/code]

EDIT: for that matter, uname has no reason to be exposed :P

**Comment by SharkWipf** [comment]
There's really no reason not to expose it either though, it increases the fun for people playing around and if someone would want to know it for some malicious reason, there's more ways to find out, and hiding the kernel version won't protect against anything.  
You did just raise another fun challenge though, I wonder if you can compile and install a new kernel in 1 command, even if it only lasts for the duration of the command. hmm...

**Comment by jarv** [comment]
@SharkWipf that is an amusing thought though the commands are fairly constrained, currently only can use up to 4MB of memory and run for about 4 seconds. BTW you can play with the sandbox if you install the docker client for OSX/Windows (or install it through your package manager for Linux), clone the repo and run `make test`. See the README for instructions.  For now the kernel version will be whatever I get from the coreos :)
