### ISSUE TITLE
grep "500" * does not work for search_for_files_containing_string

### ISSUE THREAD

**Issue by lululombard** [jarv/cmdchallenge#56]
All in the title.
It prints file names as well as the lines containing "500" but does not pass the "test".

**Comment by lululombard** [comment]
Edit : grep -rnw . -e "500" doesn't work too :/

**Comment by SharkWipf** [comment]
@lululombard This seems to be intentional, you're only asked for the file names, not the matched lines. It works fine if you only output the file names (without './' I believe, unless that's fixed in the last update).

**Comment by nugoose** [comment]
Yeah you need to output only the file name, i lost quite a bit of time last night on this, kept trying `grep -lr '500' .` and couldn't understand why it wasn't working -.-

**Comment by hauleth** [comment]
This should be fixed.

**Comment by daqo** [comment]
```
find . | grep -rl 500
```
Worked! But `grep -rl 500 .` should also be a correct answer.
