### ISSUE TITLE
New "abort-on-error" set -e functionality breaks "non-matching greps" in chains

### ISSUE THREAD

**Issue by SharkWipf** [jarv/cmdchallenge#57]
I don't think I experienced this before the last update, but since the print_common_lines challenge update, any error in a chain of commands now aborts the rest of the script.  
I.E.: 
```
bash(0)> false; echo hi
+ false
bash(1)>
```
Or, more likely to happen with these tests, a grep that doesn't match (minor spoilers?): 
```
cat somefile | while read line; do grep "otherfile" -e "$line"; done;
+ read line
+ cat somefile
+ grep otherfile -e someline
bash(1)>
```

One can work around it by adding `|| true` or `set +e`: 
```
bash(0)> cat somefile | while read line; do grep "otherfile" -e "$line" || true; done;
bash(0)>
bash(0)> set +e; cat somefile | while read line; do grep "otherfile" -e "$line"; done;
bash(0)>
```

**Comment by jarv** [comment]
What you type on the command line is copied to a script in a docker container and run with `set -e`. I guess it isn't strictly necessary and there are definitely tricks to work around it.

**Comment by jarv** [comment]
A fix for this is now live on the site, please let me know if you continue to see problems and thank you very much for the bug report!
