### ISSUE TITLE
print_common_lines: doesn't accept a correct but unsorted answer

### ISSUE THREAD

**Issue by alvarezp** [jarv/cmdchallenge#59]
Currently, `print_common_lines` challenge reads:

> access.log.1 and access.log.2 are http server logs. Print the IP addresses common to both files, one per line.

The following answer is not accepted:

```
17.137.186.194
2.71.250.27
28.151.137.59
108.68.174.15
```

but the following (which is achieved by the same command followed by `| sort`) is:

```
108.68.174.15
17.137.186.194
2.71.250.27
28.151.137.59
```

**Comment by jshort** [comment]
Lol, see #60 that I just posted :).

**Comment by alvarezp** [comment]
Yes, I found this in https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml#L7
```
#   order: whether or not order matters (optional, default is false)
```
But I see it *not* defined for `print_common_lines`. However, from looking at the code use of `order ` in `./bin/challenges.py` and noticing that the only uses of `order` in `./challenges.yaml` are `order: false`, it looks like that `order` actually defaults to `True`.

**Comment by jarv** [comment]
Good catch, you are correct that the comment in `challenges.yaml` is incorrect order actually matters by default, I made order not matter for the challenge with 58e337edd53934d926cdb9b7fa19af183cb9dc45 which will be live shortly. Thanks for the bug report!
