### ISSUE TITLE
print_common_lines needs to be further defined

### ISSUE THREAD

**Issue by jshort** [jarv/cmdchallenge#60]
See below.  My first solution is correct to the language in the challenge but was not solving it.  So I thought maybe the expectation was numerically sorted, which also did not solve the challenge.  Finally, I lexically sorted and that was correct.

For challenges where the stdout is simply compared directly to some solution text (i.e. order matters), the question should outline the order expectations.

There is a similar issue in `remove_duplicate_lines` in that a simple `cat | sort | uniq` doesn't work so on a whim, I tried an `awk` solution that maintained initial order and it was correct.
```
# You have a new challenge!
# access.log.1 and access.log.2 are http server logs. Print the IP
# addresses common to both files, one per line.
# 
bash(0)> cat access.log.1 access.log.2 | awk '($1 in array) { print $1 }; array[$1]'
17.137.186.194
2.71.250.27
28.151.137.59
108.68.174.15
bash(0)> cat access.log.1 access.log.2 | awk '($1 in array) { print $1 }; array[$1]' | sort -n
2.71.250.27
17.137.186.194
28.151.137.59
108.68.174.15
bash(0)> cat access.log.1 access.log.2 | awk '($1 in array) { print $1 }; array[$1]' | sort 
108.68.174.15
17.137.186.194
2.71.250.27
28.151.137.59
# 👍 👍 👍  Correct!
```

**Comment by dobladov** [comment]
Same problem with my solution, the question should outline the order.

`cat access.log.1 access.log.2 | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | awk 'x[$0]++'  | sort`

**Comment by jarv** [comment]
I updated print_common_lines so that order doesn't matter with 58e337edd53934d926cdb9b7fa19af183cb9dc45 . For remove_duplicate_lines I had order matter on purpose. I clarified it with 01ea3e2ac02867394fad216afaec614e3ef2228b. . Hope that addresses everything, if you have any other suggestions please let me know and thanks for bug report!
