### ISSUE TITLE
this fails

### ISSUE THREAD

**Issue by nethereal** [jarv/cmdchallenge#61]
bash(124)> grep -Ril "500" /var/challenges/search_for_files_containing_string
/var/challenges/search_for_files_containing_string/access.log
/var/challenges/search_for_files_containing_string/access.log.1
/var/challenges/search_for_files_containing_string/README

**Comment by jarv** [comment]
It's picky in that it only wants the filename, not the full path to the filename. I could make it more forgiving I guess but for now I just improved the wording with 271f6a16cdfcafb12365ab1417e2edf30a060bcc. Thanks for the issue!
