### ISSUE TITLE
remove_duplicate_lines/

### ISSUE THREAD

**Issue by TheZeke** [jarv/cmdchallenge#63]
# You have a new challenge!
# Print the file faces.txt, but only print the first instance of each
# duplicate line, even if the duplicates don't appear next to each other.
# 
bash(0)> awk '{!seen[$0]++};END{for(i in seen) if(seen[i]==1)print i}' faces.txt
♥‿♥
(ಠ⌣ಠ
¯\(°_o)/¯
(；一_一)
(͡° ͜ʖ ͡°)
ʘ‿ʘ
(ಠ‿ಠ)
(ಠ_ಠ)
◔̯◔
ಠ‿ಠ
( ﾟヮﾟ)
(^̮^)
ಠ_ಠ
⊙﹏⊙
(ʘ‿ʘ)
ಠ⌣ಠ
(° ͜ʖ °)
ಠಠ⌣ಠ)
bash(0)>

**Comment by dobladov** [comment]
My solution.
```
cat faces.txt | awk '!x[$0]++'
```

**Comment by jarv** [comment]
@TheZeke  you can also see example solutions in https://github.com/jarv/cmdchallenge/blob/master/challenges.yaml
