### ISSUE TITLE
search_for_string_in_files_recursive answer not accepted

### ISSUE THREAD

**Issue by jwbensley** [jarv/cmdchallenge#64]
UPDATE: sorry I miss-reported the issue, cleaning up....

This is report as wrong on this challenge (https://cmdchallenge.com/?twitterID=nixCraft#/search_for_string_in_files_recursive) but works on a real bash shell:

```
bash(2)> grep -o "500" -r */access.log*
+ grep -o 500 -r '*/access.log*'
grep: */access.log*: No such file or directory
```

Real bash shell:
```
bensley@ubuntu-laptop:/tmp$ ls access.log*
ls: cannot access 'access.log*': No such file or directory
bensley@ubuntu-laptop:/tmp$ ls lower/access.log*
lower/access.log2
bensley@ubuntu-laptop:/tmp$ grep "500" -r */access.log*
500
```

**Comment by jwbensley** [comment]
This also works on a real bash shell and fails on the site:

```
bash(2)> grep -o "500" -r access.log*
+ grep -o 500 -r 'access.log*'
grep: access.log*: No such file or directory
```

**Comment by jarv** [comment]
Thanks for filing an issue, can you provide a link to the challenge?

**Comment by jwbensley** [comment]
Sorry I miss-understood the challendge text, no bug here!
