### ISSUE TITLE
grep: acess.log*: No such file or directory

### ISSUE THREAD

**Issue by plainspooky** [jarv/cmdchallenge#66]
## Summary
On *Search For String In Files Recursive* challenge the files starting with "access.log" are missing.
## Steps to reproduce
Just type ```ls -la```

**Comment by jarv** [comment]
They are under the var/ dir:

```
.
./var
./var/log
./var/log/httpd
./var/log/httpd/access.log.2
./var/log/httpd/access.log
./var/log/httpd/access.log.1
```
I think the description can be improved.

**Comment by jarv** [comment]
Improved with https://github.com/jarv/cmdchallenge/commit/7c936b826e6be8d9b3622ab877ba3f56b61c9655 , thanks for the issue!
