### ISSUE TITLE
sum_all_numbers not accepting answer

### ISSUE THREAD

**Issue by jwbensley** [jarv/cmdchallenge#76]
For the sum_all_numbers question here: https://cmdchallenge.com/#/sum_all_numbers

I am using the following which works in a real bash shell:

```
james.bensley@al(tmp)$sum=0; while IFS= read -r line; do let sum=sum+"$line"; done < nums; echo $sum
15
james.bensley@al(tmp)$cat nums
1
2
3
4
5
```

This is the output on the website:

```
bash(0)> ls
README
sum-me.txt
bash(0)> $sum=0; while IFS= read -r line; do let sum=sum+"$line"; done < sum-me.txt; echo $sum
/tmp/script.sh: line 1: =0: command not found
42
bash(0)> cat sum-me.txt
1
2
3
5
7
11
13
bash(0)>
```

So the exit status is 0 (ok) but I guess it can't process multi-line commands squashed down to one line by using the semi colon `;` character ?

**Comment by jarv** [comment]
This problem might have been fixed with some my recent changes. Looks better now:

```
bash(0)> sum=0; while IFS= read -r line; do let sum=sum+"$line"; done < sum-me.txt; echo $sum
42
# 👍 👍 👍  Correct!
# You have a new challenge!
# Print all files in the current directory
# recursively without the leading directory path.
```
Please re-open if you see another issue and thanks very much for reporting this!
