### ISSUE TITLE
why didn't this work?

### ISSUE THREAD

**Issue by Qwertylex** [jarv/cmdchallenge#77]
bash(1)> find . -iname "*.txt" -print0 | xargs -0 sed -i 's/challenges\ are\ difficult//g'
Command timed out

https://cmdchallenge.com/#/replace_text_in_files

**Comment by jarv** [comment]
Technical difficulties on the site :(

```
bash(0)>  find . -iname "*.txt" -print0 | xargs -0 sed -i 's/challenges\ are\ difficult//g'
# 👍 👍 👍  Correct!
# You have a new challenge!
# The file sum-me.txt have a list of numbers,
# one per line. Print the sum of these numbers.
# 
```
Should be ok now, thanks for the issue!
