### ISSUE TITLE
print_common_lines

### ISSUE THREAD

**Issue by CorwinRU** [jarv/cmdchallenge#78]
## Summary
the following solution for last challenge is not working
```
A1=`cat access.log.1 |awk '{print $1}'`;for i in $A1; do cat access.log.2 |awk '{print $1}' | grep $i; done
```
it gives an empty output

## Steps to reproduce
https://cmdchallenge.com/#/print_common_lines

tried this solution on my mac - everything is fine. Here is a [screenshot](https://dl.dropboxusercontent.com/s/hibgujaudwuqjvm/1._Default_bash_2017-01-31_15-33-34.png?dl=0)

**Comment by jarv** [comment]
Thanks for the report,it looks like there is some more work to do here in order to make commands that return non-zero return their output properly.

**Comment by jarv** [comment]
```
bash(0)> A1=`cat access.log.1 |awk '{print $1}'`;for i in $A1; do cat access.log.2   |  awk '{print $1}' | grep  $i; done
108.68.174.15
28.151.137.59
2.71.250.27
17.137.186.194
# 👍 👍 👍  Correct!
# You have a new challenge!
# Print "hello world".
# Hint: There are many ways to print text on
# the command line, one way is with the 'echo'
# command.
# 
# Try it below and good luck!
# 
bash(1)>
```

Fixed, thanks for the issue!
