### ISSUE TITLE
remove_files_without_extension does not accept a solution with find

### ISSUE THREAD

**Issue by andrewslotin** [jarv/cmdchallenge#79]
## Summary

I've tried several approaches to solve this problem using `find` combined with `rm`, `xargs rm`, adding a `-delete` command, but none of them worked in the simulator, but it works perfectly in my bash shell on macOS:

```bash
$ ls -AR
000.txt	README	a	abc.exe	b	blog	c

./a:
.000.txt.file	0		lpha		ooo.txt.file

./a/0:
.no_extension

./b:
eta	run.go	s.txt

./c:
header.h	m

./c/m:
u.txt
$ find . -type f -and \(  -name "*.txt" -or -name "*.exe" \) -delete
$ ls -AR
README	a	b	blog	c

./a:
.000.txt.file	0		lpha		ooo.txt.file

./a/0:
.no_extension

./b:
eta	run.go

./c:
header.h	m

./c/m:
$
```

## Steps to reproduce

1. Go to https://cmdchallenge.com/#/remove_files_without_extension
2. Type in 
    ```bash
    find . -type f -and \(  -name "*.txt" -or -name "*.exe" \) -delete
    ```

**Comment by rewtnull** [comment]
You need to negate the -name "*" with a preceding ! (i.e. ! -name "*.txt" ! -name "*.exe"... Also, that -and -or construct is not necessary for this to work. In fact, negation did not work for me within this construct.

**Comment by andrewslotin** [comment]
@rewtnull, I missed the "without" part :( My apologies.
