### ISSUE TITLE
remove_extensions_from_files

### ISSUE THREAD

**Issue by mmalchuk** [jarv/cmdchallenge#80]
## Steps to reproduce

https://cmdchallenge.com/#/remove_extensions_from_files

```
# Remove the extension from all files in
# the current directory recursively.
# 
bash(0)> find * -type f | sed -e's/^\(.*\/\)*\(.*\..*\)$/\2/g' | sed -e's/\(.*\)\..*/\1/g'
corporis
odit
animi
README
beatae
error
libero
necessitatibus
totam
Test failed, there are still files with extensions in the current directory.
```

wish you're will fix this )

**Comment by mmalchuk** [comment]
lol, please update the description. add the word 'rename'. this is not an obvious how a user should remove the extension! only print on screen or from the files on the filesystem)

**Comment by jarv** [comment]
@mmalchuk  thanks for the issue, I will see if I can improve it. Also feel free to send a PR :)

**Comment by jarv** [comment]
Thanks!
