### ISSUE TITLE
rm -rf `pwd`: Unknown Error

### ISSUE THREAD

**Issue by seymour1** [jarv/cmdchallenge#83]
## Summary
running rm -rf \`pwd\` gives an unknown error and explodes the shell, when it should solve the delete_files problem.

## Steps to reproduce
If applicable please provide a direct link to the challenge, example: https://cmdchallenge.com/#/delete_files

**Comment by jarv** [comment]
thanks for the issue. The challenge should probably be more specific in that you only want to delete everything beneath the working directory, not everything including the directory itself.

**Comment by seymour1** [comment]
If that's the case, then shouldn't rm -rf -- ./* work as well? That fails the test.

**Comment by jarv** [comment]
The '*' glob won't capture files or directories starting with a '.'

**Comment by seymour1** [comment]
Learned something new, thanks!
