### ISSUE TITLE
search_for_files_containing_string does'nt accept solution $ grep -R 500 . | cut -d : -f1 | cut -d / -f2

### ISSUE THREAD

**Issue by mpiffault** [jarv/cmdchallenge#96]
https://cmdchallenge.com/#/search_for_files_containing_string does not accept the solution:

`grep -R 500 . | cut -d : -f1 | cut -d / -f2`

wich is ugly, but works !

**Comment by avioli** [comment]
You get multiple instances of the same file. You either have to instruct grep to show only one result from each file or show unique lines at the end.

**Comment by mpiffault** [comment]
Indeed ! Read the result too quickly...
