### ISSUE TITLE
rm -rf on delete_files

### ISSUE THREAD

**Issue by limkokhole** [jarv/cmdchallenge#98]
## Summary
rm -rf should work on question delete_files

## Steps to reproduce:
1. Visits https://cmdchallenge.com/#/delete_files
2. `rm -rf ./*` was failed, but `find . delete` success.

**Comment by limkokhole** [comment]
Typo: `find . delete` should be -delete

**Comment by branning** [comment]
I believe `rm -rf *` should also pass.

**Comment by Sacro** [comment]
rm -rf *.* 

Should do the job however.

**Comment by 0ki** [comment]
What about files that don't contain a dot?

**Comment by jarv** [comment]
@limkokhole thanks for the issue, there might be some wording improvements for this challenge to make it clearer as it is a little tricky. If you have any please feel free to make them or even better submit a PR. Thanks!
